// Generated by gencpp from file rrt_planning/CommMsg.msg
// DO NOT EDIT!


#ifndef RRT_PLANNING_MESSAGE_COMMMSG_H
#define RRT_PLANNING_MESSAGE_COMMMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rrt_planning
{
template <class ContainerAllocator>
struct CommMsg_
{
  typedef CommMsg_<ContainerAllocator> Type;

  CommMsg_()
    : cellX(0)
    , cellY(0)
    , uploadTime(0)  {
    }
  CommMsg_(const ContainerAllocator& _alloc)
    : cellX(0)
    , cellY(0)
    , uploadTime(0)  {
  (void)_alloc;
    }



   typedef uint32_t _cellX_type;
  _cellX_type cellX;

   typedef uint32_t _cellY_type;
  _cellY_type cellY;

   typedef uint32_t _uploadTime_type;
  _uploadTime_type uploadTime;




  typedef boost::shared_ptr< ::rrt_planning::CommMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rrt_planning::CommMsg_<ContainerAllocator> const> ConstPtr;

}; // struct CommMsg_

typedef ::rrt_planning::CommMsg_<std::allocator<void> > CommMsg;

typedef boost::shared_ptr< ::rrt_planning::CommMsg > CommMsgPtr;
typedef boost::shared_ptr< ::rrt_planning::CommMsg const> CommMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rrt_planning::CommMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rrt_planning::CommMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rrt_planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rrt_planning': ['/home/arlind/Desktop/Workspace/RosProj/Planning/src/Planning/rrt_planning/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rrt_planning::CommMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rrt_planning::CommMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rrt_planning::CommMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rrt_planning::CommMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrt_planning::CommMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrt_planning::CommMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rrt_planning::CommMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ae8e81eb815f3fe2d8493f75b85e1c9";
  }

  static const char* value(const ::rrt_planning::CommMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ae8e81eb815f3feULL;
  static const uint64_t static_value2 = 0x2d8493f75b85e1c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rrt_planning::CommMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rrt_planning/CommMsg";
  }

  static const char* value(const ::rrt_planning::CommMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rrt_planning::CommMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
uint32  cellX	\n\
uint32  cellY\n\
uint32 uploadTime\n\
";
  }

  static const char* value(const ::rrt_planning::CommMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rrt_planning::CommMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cellX);
      stream.next(m.cellY);
      stream.next(m.uploadTime);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CommMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rrt_planning::CommMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rrt_planning::CommMsg_<ContainerAllocator>& v)
  {
    s << indent << "cellX: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.cellX);
    s << indent << "cellY: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.cellY);
    s << indent << "uploadTime: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.uploadTime);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RRT_PLANNING_MESSAGE_COMMMSG_H
